version: '3'

services:
  app:
    build: .
    command: ./.docker/start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      # - '/etc/timezone:/etc/timezone:ro'
      # - '/etc/localtime:/etc/localtime:ro'
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # labels:
    #   filebeat_collector: true